### ISSUE TITLE
[ContentFragment] Follow-up tasks after the move to Core Components

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#516]
The content fragment component has been moved from `extension` to the Core Components. The content fragment list component has been added to the Core Components.

The following tasks still need to be performed before a release of those two components:

- [x] create a page in the component library for the content fragment list component (#525)
- [x] write JUnit tests for the JSON export of the content fragment and the content fragment list component (#521)
- [x] write UI tests for the content fragment (#524) and the content fragment list (#522) components. 
- [x] integrate the feedback from the PRs that could not be integrated (due to time constraints):
https://github.com/adobe/aem-core-wcm-components/pull/499
https://github.com/adobe/aem-core-wcm-components/pull/502
- ~~fix the creation year to 2019 in the source code of the content fragment list~~ 
- [x] verify the github READMEs that reference the content fragment
- [x] create a README for the content fragment list component (#523)

**Additionally**
- update the content fragment component in We.Retail (CQ-4266578)
- use the content fragment list component in We.Retail (CQ-4266576)
- update the Adobe docs for the content fragment component
https://docs.adobe.com/content/help/en/experience-manager-core-components/using/components/content-fragment-component.html (CQ-4266574, CQDOC-14281)
- write new Adobe docs for the content fragment list component (CQDOC-14278)

**Comment by jckautzmann** [comment]
(CQ-4266267)

**Comment by richardhand** [comment]
Created individual tasks to break this down a bit. Suggest we handle `integrate the feedback from the PRs that could not be integrated (due to time constraints)` here and the rest elsewhere. Added the issue references in the description.

**Comment by richardhand** [comment]
This is available on the master branch and will be included in the upcoming [2.4.0](https://github.com/adobe/aem-core-wcm-components/milestone/11) release.
